INSERT INTO obj_dependency(ID, INSTALLED, OBJ, DEPENDENT_ON) VALUES(0, false, 'NETCARD', '');
INSERT INTO obj_dependency(ID, INSTALLED, OBJ, DEPENDENT_ON) VALUES(1, false, 'TCPIP', 'NETCARD');
INSERT INTO obj_dependency(ID, INSTALLED, OBJ, DEPENDENT_ON) VALUES(2, false, 'TELNET', 'TCPIP');

INSERT INTO obj_dependency(ID, INSTALLED, OBJ, DEPENDENT_ON) VALUES(3, false, 'DNS', 'TCPIP');
INSERT INTO obj_dependency(ID, INSTALLED, OBJ, DEPENDENT_ON) VALUES(4, false, 'ESPECIAL_LIB', '');
INSERT INTO obj_dependency(ID, INSTALLED, OBJ, DEPENDENT_ON) VALUES(3, false, 'DNS', 'ESPECIAL_LIB');

INSERT INTO obj_dependency(ID, INSTALLED, OBJ, DEPENDENT_ON) VALUES(5, false, 'HTTP', 'TCPIP');
INSERT INTO obj_dependency(ID, INSTALLED, OBJ, DEPENDENT_ON) VALUES(6, false, 'BROWSER', 'HTTP');
